### ISSUE TITLE
common_front_board_list_form_gallery

### ISSUE THREAD

**Issue by chonapllido** [chonapllido/stm_component_practice#15]
make
1. common_front_board_list_form_gallery_empty_data
2. common_front_board_list_from_gallery1_no_writer
3. common_front_board_list_form_gallery1_writer_division
4. common_front_board_list_form_gallery1_writer_user

Assignee: Kass

**Comment by cabacangwork** [comment]
Done:

1.common_front_board_list_form_gallery_empty_data

**Comment by cabacangwork** [comment]
Done 
1. common_front_board_list_form_gallery_empty_data
2. common_front_board_list_from_gallery1_no_writer
3. common_front_board_list_form_gallery1_writer_division
4. common_front_board_list_form_gallery1_writer_user

**Comment by chonapllido** [comment]
use <table> instead of <ul>

**Comment by cabacangwork** [comment]
Updates Done
