### ISSUE TITLE
common_front_board_list_top

### ISSUE THREAD

**Issue by chonapllido** [chonapllido/stm_component_practice#9]
make:
1. common_front_board_list_top

Assignee: Kass

**Comment by cabacangwork** [comment]
Done

**Comment by chonapllido** [comment]
check in IE 9

**Comment by cabacangwork** [comment]
Fixes Done

**Comment by chonapllido** [comment]
1.
![board_list_top](https://user-images.githubusercontent.com/25450965/59829133-2f8e0400-936f-11e9-9e1e-873c718e6c08.png)

2.
![board_list_top2](https://user-images.githubusercontent.com/25450965/59829138-3288f480-936f-11e9-8992-daf7a009de8d.png)

**Comment by cabacangwork** [comment]
Fixes Done
